2024-02-01 13:32:34,368 INFO    MainThread:130134 [wandb_setup.py:_flush():76] Current SDK version is 0.16.2
2024-02-01 13:32:34,368 INFO    MainThread:130134 [wandb_setup.py:_flush():76] Configure stats pid to 130134
2024-02-01 13:32:34,368 INFO    MainThread:130134 [wandb_setup.py:_flush():76] Loading settings from /user/gent/457/vsc45787/.config/wandb/settings
2024-02-01 13:32:34,368 INFO    MainThread:130134 [wandb_setup.py:_flush():76] Loading settings from /kyukon/home/gent/457/vsc45787/bsc/Centralized controller/wandb/settings
2024-02-01 13:32:34,368 INFO    MainThread:130134 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-02-01 13:32:34,368 INFO    MainThread:130134 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-02-01 13:32:34,369 INFO    MainThread:130134 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-02-01 13:32:34,369 INFO    MainThread:130134 [wandb_init.py:_log_setup():526] Logging user logs to /kyukon/home/gent/457/vsc45787/bsc/Centralized controller/wandb/run-20240201_133234-0hrj2dvj/logs/debug.log
2024-02-01 13:32:34,369 INFO    MainThread:130134 [wandb_init.py:_log_setup():527] Logging internal logs to /kyukon/home/gent/457/vsc45787/bsc/Centralized controller/wandb/run-20240201_133234-0hrj2dvj/logs/debug-internal.log
2024-02-01 13:32:34,369 INFO    MainThread:130134 [wandb_init.py:_jupyter_setup():472] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x148f8eefaf90>
2024-02-01 13:32:34,369 INFO    MainThread:130134 [wandb_init.py:init():566] calling init triggers
2024-02-01 13:32:34,369 INFO    MainThread:130134 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.02, 'architecture': 'CNN', 'dataset': 'CIFAR-100', 'epochs': 10}
2024-02-01 13:32:34,369 INFO    MainThread:130134 [wandb_init.py:init():591] re-initializing run, found existing run on stack: eabkkl5e
2024-02-01 13:32:34,370 INFO    MainThread:130134 [wandb_run.py:_finish():1962] finishing run matthias-pex/Centralized controller framework/eabkkl5e
2024-02-01 13:32:34,370 INFO    MainThread:130134 [wandb_run.py:_atexit_cleanup():2202] got exitcode: 0
2024-02-01 13:32:34,370 INFO    MainThread:130134 [wandb_run.py:_restore():2185] restore
2024-02-01 13:32:34,370 INFO    MainThread:130134 [wandb_run.py:_restore():2191] restore done
2024-02-01 13:32:37,688 INFO    MainThread:130134 [wandb_run.py:_footer_history_summary_info():3857] rendering history
2024-02-01 13:32:37,689 INFO    MainThread:130134 [wandb_run.py:_footer_history_summary_info():3889] rendering summary
2024-02-01 13:32:37,691 INFO    MainThread:130134 [wandb_run.py:_footer_sync_info():3816] logging synced files
2024-02-01 13:32:37,710 INFO    MainThread:130134 [wandb_init.py:init():616] starting backend
2024-02-01 13:32:37,710 INFO    MainThread:130134 [wandb_init.py:init():620] setting up manager
2024-02-01 13:32:37,711 INFO    MainThread:130134 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-02-01 13:32:37,712 INFO    MainThread:130134 [wandb_init.py:init():628] backend started and connected
2024-02-01 13:32:37,716 INFO    MainThread:130134 [wandb_run.py:_label_probe_notebook():1294] probe notebook
2024-02-01 13:32:37,716 INFO    MainThread:130134 [wandb_run.py:_label_probe_notebook():1304] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-02-01 13:32:37,716 INFO    MainThread:130134 [wandb_init.py:init():720] updated telemetry
2024-02-01 13:32:37,729 INFO    MainThread:130134 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-02-01 13:32:39,079 INFO    MainThread:130134 [wandb_run.py:_on_init():2254] communicating current version
2024-02-01 13:32:39,139 INFO    MainThread:130134 [wandb_run.py:_on_init():2263] got version response 
2024-02-01 13:32:39,140 INFO    MainThread:130134 [wandb_init.py:init():804] starting run threads in backend
2024-02-01 13:32:39,976 INFO    MainThread:130134 [wandb_run.py:_console_start():2233] atexit reg
2024-02-01 13:32:39,977 INFO    MainThread:130134 [wandb_run.py:_redirect():2088] redirect: wrap_raw
2024-02-01 13:32:39,977 INFO    MainThread:130134 [wandb_run.py:_redirect():2153] Wrapping output streams.
2024-02-01 13:32:39,977 INFO    MainThread:130134 [wandb_run.py:_redirect():2178] Redirects installed.
2024-02-01 13:32:39,977 INFO    MainThread:130134 [wandb_init.py:init():847] run started, returning control to user process
2024-02-01 13:40:47,178 INFO    MainThread:130134 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-02-01 13:40:47,178 INFO    MainThread:130134 [wandb_init.py:_pause_backend():437] pausing backend
2024-02-01 13:41:00,954 INFO    MainThread:130134 [wandb_init.py:_resume_backend():442] resuming backend
2024-02-01 13:41:01,531 INFO    MainThread:130134 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-02-01 13:41:01,531 INFO    MainThread:130134 [wandb_init.py:_pause_backend():437] pausing backend
2024-02-01 13:41:01,544 INFO    MainThread:130134 [wandb_init.py:_resume_backend():442] resuming backend
2024-02-01 13:41:27,771 INFO    MainThread:130134 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-02-01 13:41:27,772 INFO    MainThread:130134 [wandb_init.py:_pause_backend():437] pausing backend
2024-02-01 13:41:27,776 INFO    MainThread:130134 [wandb_init.py:_resume_backend():442] resuming backend
2024-02-01 13:41:27,800 INFO    MainThread:130134 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-02-01 13:41:27,800 INFO    MainThread:130134 [wandb_init.py:_pause_backend():437] pausing backend
2024-02-01 13:41:27,804 INFO    MainThread:130134 [wandb_init.py:_resume_backend():442] resuming backend
2024-02-01 13:41:28,076 INFO    MainThread:130134 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-02-01 13:41:28,076 INFO    MainThread:130134 [wandb_init.py:_pause_backend():437] pausing backend
2024-02-01 13:42:44,859 INFO    MainThread:130134 [wandb_init.py:_resume_backend():442] resuming backend
2024-02-01 13:42:44,876 INFO    MainThread:130134 [wandb_setup.py:_flush():76] Current SDK version is 0.16.2
2024-02-01 13:42:44,876 INFO    MainThread:130134 [wandb_setup.py:_flush():76] Configure stats pid to 130134
2024-02-01 13:42:44,876 INFO    MainThread:130134 [wandb_setup.py:_flush():76] Loading settings from /user/gent/457/vsc45787/.config/wandb/settings
2024-02-01 13:42:44,876 INFO    MainThread:130134 [wandb_setup.py:_flush():76] Loading settings from /kyukon/home/gent/457/vsc45787/bsc/Centralized controller/wandb/settings
2024-02-01 13:42:44,876 INFO    MainThread:130134 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-02-01 13:42:44,876 INFO    MainThread:130134 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-02-01 13:42:44,876 INFO    MainThread:130134 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-02-01 13:42:44,876 INFO    MainThread:130134 [wandb_init.py:_log_setup():526] Logging user logs to /kyukon/home/gent/457/vsc45787/bsc/Centralized controller/wandb/run-20240201_134244-qnmxx7ds/logs/debug.log
2024-02-01 13:42:44,876 INFO    MainThread:130134 [wandb_init.py:_log_setup():527] Logging internal logs to /kyukon/home/gent/457/vsc45787/bsc/Centralized controller/wandb/run-20240201_134244-qnmxx7ds/logs/debug-internal.log
2024-02-01 13:42:44,877 INFO    MainThread:130134 [wandb_init.py:init():566] calling init triggers
2024-02-01 13:42:44,877 INFO    MainThread:130134 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {'learning_rate': 0.02, 'architecture': 'CNN', 'dataset': 'CIFAR-100', 'epochs': 10}
2024-02-01 13:42:44,877 INFO    MainThread:130134 [wandb_init.py:init():591] re-initializing run, found existing run on stack: 0hrj2dvj
2024-02-01 13:42:44,878 INFO    MainThread:130134 [wandb_run.py:_finish():1962] finishing run matthias-pex/Centralized controller framework/0hrj2dvj
2024-02-01 13:42:44,878 INFO    MainThread:130134 [jupyter.py:save_history():445] not saving jupyter history
2024-02-01 13:42:44,878 INFO    MainThread:130134 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-02-01 13:42:44,878 INFO    MainThread:130134 [wandb_init.py:_jupyter_teardown():454] cleaning up jupyter logic
2024-02-01 13:42:44,878 INFO    MainThread:130134 [wandb_run.py:_atexit_cleanup():2202] got exitcode: 0
2024-02-01 13:42:44,879 INFO    MainThread:130134 [wandb_run.py:_restore():2185] restore
2024-02-01 13:42:44,879 INFO    MainThread:130134 [wandb_run.py:_restore():2191] restore done
2024-02-01 13:42:49,688 INFO    MainThread:130134 [wandb_run.py:_footer_history_summary_info():3857] rendering history
2024-02-01 13:42:49,689 INFO    MainThread:130134 [wandb_run.py:_footer_history_summary_info():3889] rendering summary
2024-02-01 13:42:49,692 INFO    MainThread:130134 [wandb_run.py:_footer_sync_info():3816] logging synced files
